import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { io, Socket } from "socket.io-client";
import { DefaultEventsMap } from "socket.io-client/build/typed-events";
import { serverEndPoint } from "../constants";
import { useAppContext } from "../state";

import styles from "../styles/Home.module.scss";

interface form {
  name: string;
  room: string;
}

export default function Home() {
  const router = useRouter();
  const {
    value: { name, room },
    setValue,
    socket,
  } = useAppContext();

  const {
    register,
    handleSubmit,
    formState: { isDirty, isSubmitting, isValid },
  } = useForm<form>({ mode: "onChange" });

  //submit function
  const submit = (data: form) => {
    setValue(data);
    socket.emit("room", { room: data.room, name: data.name });
    router.push("/chat");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={handleSubmit(submit)}>
        <label>
          name:
          <input type="text" {...register("name")} />
        </label>
        <label>
          room:
          <input type="text" {...register("room")} />
        </label>
        <button disabled={!isDirty || !isValid || isSubmitting} type="submit">
          submit
        </button>
      </form>
    </div>
  );
}
